ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  ssh:
    port: 22
    expose:
      default: true
    exposedPort: 22
    protocol: TCP
